# Build and test Jekyll site
name: Build and test website

on:
  push:
    branches:
      - main
  schedule:
    # run weekly
    - cron: '0 10 * * 2'
  pull_request:
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Build and test
        run: bundle exec rake test
      - name: Test paper links
        run: bundle exec rake test_paper_links
